import { Box, Divider, Typography } from "@mui/material";
import Head from "next/head";
import { useContext, useEffect, useState } from "react";
import Contact from "../components/routes/home/contact/Contact";
import Features from "../components/routes/home/features/Features";
import Footer from "../components/routes/home/footer/Footer";
import Header from "../components/routes/home/header/Header";
import Main from "../components/routes/home/main/Main";
import Portfolio from "../components/routes/home/portfolio/Portfolio";
import Pricing from "../components/routes/home/pricing/Pricing";
import Resume from "../components/routes/home/resume/Resume";
import Testimonial from "../components/routes/home/testimonial/Testimonial";
import { Context } from "./_app";

export default function Home() {
  const colorMode = useContext(Context);
  const [location, setLocation] = useState({
    homeY: 0,
    featuresY: 0,
    portfolioY: 0,
    resumeY: 0,
    testimonialY: 0,
    pricingY: 0,
    contactY: 0,
  });

  useEffect(() => {
    const homeY = Number(window.document.getElementById("Home")?.offsetTop);
    const featuresY =
      Number(window.document.getElementById("Features")?.offsetTop) - 120;
    const portfolioY =
      Number(window.document.getElementById("Portfolio")?.offsetTop) - 120;
    const resumeY =
      Number(window.document.getElementById("Resume")?.offsetTop) - 120;
    const testimonialY =
      Number(window.document.getElementById("Testimonial")?.offsetTop) - 120;
    const pricingY =
      Number(window.document.getElementById("Pricing")?.offsetTop) - 120;
    const contactY =
      Number(window.document.getElementById("Contact")?.offsetTop) - 120;

    setLocation({
      homeY,
      featuresY,
      portfolioY,
      resumeY,
      testimonialY,
      pricingY,
      contactY,
    });
  }, []);

  return (
    <Box
      sx={{ bgcolor: colorMode.colorTheme === "dark" ? "#212428" : "#ecf0f3" }}
    >
      <Head>
        <title>personal site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header location={location} />
      <main>
        <Main />
        <Divider sx={{ my: 7, maxWidth: 1200, mx: "auto" }} />
        <Features />
        <Divider sx={{ my: 5, maxWidth: 1200, mx: "auto" }} />
        <Portfolio />
        <Divider sx={{ my: 5, maxWidth: 1200, mx: "auto" }} />
        <Resume />
        <Divider sx={{ my: 5, maxWidth: 1200, mx: "auto" }} />
        <Testimonial />
        <Divider sx={{ my: 5, maxWidth: 1200, mx: "auto" }} />
        <Pricing />
        <Divider sx={{ my: 5, maxWidth: 1200, mx: "auto" }} />
        <Contact />
        <Divider sx={{ my: 12, maxWidth: 1200, mx: "auto" }} />
      </main>
      <Footer />
    </Box>
  );
}
