import { Box, Divider, Typography } from '@mui/material'
import Head from 'next/head'
import { useContext } from 'react';
import Features from '../components/routes/home/features/Features';
import Header from '../components/routes/home/header/Header'
import Main from '../components/routes/home/main/Main';
import { Context } from './_app';

export default function Home() {
  const colorMode = useContext(Context);
  return (
    <Box sx={{ bgcolor: colorMode.colorTheme === 'dark' ? "#212428" : '#ecf0f3' }}>
      <Head>
        <title>personal site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <Main />
        <Divider sx={{ my: 7, maxWidth: 1200, mx: 'auto' }} />
        <Features />
        <Divider sx={{ my: 7, maxWidth: 1200, mx: 'auto' }} />
      </main>
    </Box>
  )
}
